const { DynamoDBClient } = require('@aws-sdk/client-dynamodb');
const { DynamoDBDocumentClient, PutCommand } = require('@aws-sdk/lib-dynamodb');
require('dotenv').config();

const client = new DynamoDBClient({ region: process.env.AWS_REGION });
const docClient = DynamoDBDocumentClient.from(client);

// list game was created by Claude
const games = [
    { gameId: '1', name: 'Catan', yearPublished: 1995, minPlayers: 3, maxPlayers: 4, playingTime: 90, rating: 7.1, complexity: 2.3 },
    { gameId: '2', name: 'Ticket to Ride', yearPublished: 2004, minPlayers: 2, maxPlayers: 5, playingTime: 60, rating: 7.4, complexity: 1.8 },
    { gameId: '3', name: 'Pandemic', yearPublished: 2008, minPlayers: 2, maxPlayers: 4, playingTime: 45, rating: 7.6, complexity: 2.4 },
    { gameId: '4', name: '7 Wonders', yearPublished: 2010, minPlayers: 2, maxPlayers: 7, playingTime: 30, rating: 7.7, complexity: 2.3 },
    { gameId: '5', name: 'Splendor', yearPublished: 2014, minPlayers: 2, maxPlayers: 4, playingTime: 30, rating: 7.4, complexity: 1.8 },
    { gameId: '6', name: 'Terraforming Mars', yearPublished: 2016, minPlayers: 1, maxPlayers: 5, playingTime: 120, rating: 8.4, complexity: 3.2 },
    { gameId: '7', name: 'Brass: Birmingham', yearPublished: 2018, minPlayers: 2, maxPlayers: 4, playingTime: 120, rating: 8.6, complexity: 3.9 },
    { gameId: '8', name: 'Wingspan', yearPublished: 2019, minPlayers: 1, maxPlayers: 5, playingTime: 70, rating: 8.1, complexity: 2.4 },
    { gameId: '9', name: 'Carcassonne', yearPublished: 2000, minPlayers: 2, maxPlayers: 5, playingTime: 45, rating: 7.4, complexity: 1.9 },
    { gameId: '10', name: 'Agricola', yearPublished: 2007, minPlayers: 1, maxPlayers: 5, playingTime: 120, rating: 7.9, complexity: 3.6 },
    { gameId: '11', name: 'Codenames', yearPublished: 2015, minPlayers: 2, maxPlayers: 8, playingTime: 15, rating: 7.6, complexity: 1.3 },
    { gameId: '12', name: 'Power Grid', yearPublished: 2004, minPlayers: 2, maxPlayers: 6, playingTime: 120, rating: 7.8, complexity: 3.3 },
    { gameId: '13', name: 'Dominion', yearPublished: 2008, minPlayers: 2, maxPlayers: 4, playingTime: 30, rating: 7.6, complexity: 2.3 },
    { gameId: '14', name: '7 Wonders Duel', yearPublished: 2015, minPlayers: 2, maxPlayers: 2, playingTime: 30, rating: 8.1, complexity: 2.2 },
    { gameId: '15', name: 'The Crew: The Quest for Planet Nine', yearPublished: 2019, minPlayers: 2, maxPlayers: 5, playingTime: 20, rating: 7.9, complexity: 1.9 },
    { gameId: '16', name: 'Everdell', yearPublished: 2018, minPlayers: 1, maxPlayers: 4, playingTime: 80, rating: 8.1, complexity: 2.8 },
    { gameId: '17', name: 'Scythe', yearPublished: 2016, minPlayers: 1, maxPlayers: 5, playingTime: 115, rating: 8.2, complexity: 3.4 },
    { gameId: '18', name: 'Star Wars: Rebellion', yearPublished: 2016, minPlayers: 2, maxPlayers: 4, playingTime: 240, rating: 8.5, complexity: 3.7 },
    { gameId: '19', name: 'Twilight Struggle', yearPublished: 2005, minPlayers: 2, maxPlayers: 2, playingTime: 180, rating: 8.3, complexity: 3.6 },
    { gameId: '20', name: 'Star Wars: Imperial Assault', yearPublished: 2014, minPlayers: 1, maxPlayers: 5, playingTime: 120, rating: 8.1, complexity: 3.1 },
    { gameId: '21', name: 'Terra Mystica', yearPublished: 2012, minPlayers: 2, maxPlayers: 5, playingTime: 150, rating: 8.1, complexity: 4.0 },
    { gameId: '22', name: 'Le Havre', yearPublished: 2008, minPlayers: 1, maxPlayers: 5, playingTime: 150, rating: 7.9, complexity: 3.7 },
    { gameId: '23', name: 'Puerto Rico', yearPublished: 2002, minPlayers: 2, maxPlayers: 5, playingTime: 150, rating: 8.0, complexity: 3.3 },
    { gameId: '24', name: 'Android: Netrunner', yearPublished: 2012, minPlayers: 2, maxPlayers: 2, playingTime: 45, rating: 8.3, complexity: 3.3 },
    { gameId: '25', name: 'Caverna: The Cave Farmers', yearPublished: 2013, minPlayers: 1, maxPlayers: 7, playingTime: 150, rating: 8.1, complexity: 3.5 },
    { gameId: '26', name: 'Mage Knight Board Game', yearPublished: 2011, minPlayers: 1, maxPlayers: 4, playingTime: 150, rating: 8.3, complexity: 4.1 },
    { gameId: '27', name: 'Caylus', yearPublished: 2005, minPlayers: 2, maxPlayers: 5, playingTime: 150, rating: 7.7, complexity: 3.5 },
    { gameId: '28', name: 'That\'s Pretty Clever!', yearPublished: 2018, minPlayers: 1, maxPlayers: 4, playingTime: 20, rating: 7.7, complexity: 1.9 },
    { gameId: '29', name: 'Cascadia', yearPublished: 2021, minPlayers: 1, maxPlayers: 4, playingTime: 40, rating: 8.1, complexity: 1.9 },
    { gameId: '30', name: 'Lost Ruins of Arnak', yearPublished: 2020, minPlayers: 1, maxPlayers: 4, playingTime: 90, rating: 8.1, complexity: 2.9 },
    { gameId: '31', name: 'Azul', yearPublished: 2017, minPlayers: 2, maxPlayers: 4, playingTime: 45, rating: 7.8, complexity: 1.8 },
    { gameId: '32', name: 'Root', yearPublished: 2018, minPlayers: 2, maxPlayers: 4, playingTime: 90, rating: 8.1, complexity: 3.8 },
    { gameId: '33', name: 'Gloomhaven', yearPublished: 2017, minPlayers: 1, maxPlayers: 4, playingTime: 120, rating: 8.6, complexity: 3.9 },
    { gameId: '34', name: 'Spirit Island', yearPublished: 2017, minPlayers: 1, maxPlayers: 4, playingTime: 120, rating: 8.3, complexity: 4.0 },
    { gameId: '35', name: 'Viticulture Essential Edition', yearPublished: 2015, minPlayers: 1, maxPlayers: 6, playingTime: 90, rating: 7.9, complexity: 2.9 },
    { gameId: '36', name: 'Concordia', yearPublished: 2013, minPlayers: 2, maxPlayers: 5, playingTime: 100, rating: 8.0, complexity: 3.0 },
    { gameId: '37', name: 'Great Western Trail', yearPublished: 2016, minPlayers: 2, maxPlayers: 4, playingTime: 150, rating: 8.3, complexity: 3.6 },
    { gameId: '38', name: 'Through the Ages: A New Story of Civilization', yearPublished: 2015, minPlayers: 2, maxPlayers: 4, playingTime: 180, rating: 8.4, complexity: 4.4 },
    { gameId: '39', name: 'Gaia Project', yearPublished: 2017, minPlayers: 1, maxPlayers: 4, playingTime: 150, rating: 8.4, complexity: 4.4 },
    { gameId: '40', name: 'Clank!: A Deck-Building Adventure', yearPublished: 2016, minPlayers: 2, maxPlayers: 4, playingTime: 60, rating: 7.7, complexity: 2.1 },
    { gameId: '41', name: 'War of the Ring', yearPublished: 2004, minPlayers: 2, maxPlayers: 4, playingTime: 180, rating: 8.4, complexity: 4.1 },
    { gameId: '42', name: 'A Feast for Odin', yearPublished: 2016, minPlayers: 1, maxPlayers: 4, playingTime: 120, rating: 8.3, complexity: 3.8 },
    { gameId: '43', name: 'Barrage', yearPublished: 2019, minPlayers: 1, maxPlayers: 4, playingTime: 120, rating: 8.3, complexity: 4.2 },
    { gameId: '44', name: 'Tzolk\'in: The Mayan Calendar', yearPublished: 2012, minPlayers: 2, maxPlayers: 4, playingTime: 90, rating: 7.8, complexity: 3.4 },
    { gameId: '45', name: 'Suburbia', yearPublished: 2012, minPlayers: 1, maxPlayers: 4, playingTime: 90, rating: 7.5, complexity: 2.8 },
    { gameId: '46', name: 'Five Tribes', yearPublished: 2014, minPlayers: 2, maxPlayers: 4, playingTime: 80, rating: 7.7, complexity: 2.9 },
    { gameId: '47', name: 'Century: Spice Road', yearPublished: 2017, minPlayers: 2, maxPlayers: 5, playingTime: 40, rating: 7.3, complexity: 1.8 },
    { gameId: '48', name: 'Patchwork', yearPublished: 2014, minPlayers: 2, maxPlayers: 2, playingTime: 30, rating: 7.6, complexity: 1.6 },
    { gameId: '49', name: 'Sushi Go!', yearPublished: 2013, minPlayers: 2, maxPlayers: 5, playingTime: 15, rating: 7.1, complexity: 1.2 },
    { gameId: '50', name: 'Love Letter', yearPublished: 2012, minPlayers: 2, maxPlayers: 4, playingTime: 20, rating: 7.0, complexity: 1.2 },
    { gameId: '51', name: 'Hanabi', yearPublished: 2010, minPlayers: 2, maxPlayers: 5, playingTime: 25, rating: 7.2, complexity: 1.8 },
    { gameId: '52', name: 'Coup', yearPublished: 2012, minPlayers: 2, maxPlayers: 6, playingTime: 15, rating: 7.4, complexity: 1.4 },
    { gameId: '53', name: 'The Resistance', yearPublished: 2009, minPlayers: 5, maxPlayers: 10, playingTime: 30, rating: 7.4, complexity: 1.6 },
    { gameId: '54', name: 'Bang!', yearPublished: 2002, minPlayers: 4, maxPlayers: 7, playingTime: 40, rating: 7.1, complexity: 1.8 },
    { gameId: '55', name: 'Small World', yearPublished: 2009, minPlayers: 2, maxPlayers: 5, playingTime: 80, rating: 7.3, complexity: 2.3 },
    { gameId: '56', name: 'King of Tokyo', yearPublished: 2011, minPlayers: 2, maxPlayers: 6, playingTime: 30, rating: 7.2, complexity: 1.5 },
    { gameId: '57', name: 'Machi Koro', yearPublished: 2012, minPlayers: 2, maxPlayers: 4, playingTime: 30, rating: 7.0, complexity: 1.5 },
    { gameId: '58', name: 'Forbidden Island', yearPublished: 2010, minPlayers: 2, maxPlayers: 4, playingTime: 30, rating: 6.8, complexity: 1.6 },
    { gameId: '59', name: 'Forbidden Desert', yearPublished: 2013, minPlayers: 2, maxPlayers: 5, playingTime: 45, rating: 7.2, complexity: 1.9 },
    { gameId: '60', name: 'Dead of Winter', yearPublished: 2014, minPlayers: 2, maxPlayers: 5, playingTime: 120, rating: 7.7, complexity: 2.8 },
    { gameId: '61', name: 'Betrayal at House on the Hill', yearPublished: 2004, minPlayers: 3, maxPlayers: 6, playingTime: 60, rating: 6.8, complexity: 1.9 },
    { gameId: '62', name: 'Arkham Horror', yearPublished: 2005, minPlayers: 1, maxPlayers: 8, playingTime: 240, rating: 7.3, complexity: 3.1 },
    { gameId: '63', name: 'Eldritch Horror', yearPublished: 2013, minPlayers: 1, maxPlayers: 8, playingTime: 120, rating: 7.8, complexity: 3.0 },
    { gameId: '64', name: 'Mansions of Madness (2nd Edition)', yearPublished: 2016, minPlayers: 1, maxPlayers: 5, playingTime: 120, rating: 8.1, complexity: 2.9 },
    { gameId: '65', name: 'Descent: Journeys in the Dark (2nd Edition)', yearPublished: 2012, minPlayers: 2, maxPlayers: 5, playingTime: 120, rating: 8.0, complexity: 2.8 },
    { gameId: '66', name: 'Zombicide', yearPublished: 2012, minPlayers: 1, maxPlayers: 6, playingTime: 60, rating: 7.7, complexity: 2.1 },
    { gameId: '67', name: 'Blood Rage', yearPublished: 2015, minPlayers: 2, maxPlayers: 4, playingTime: 90, rating: 8.2, complexity: 2.8 },
    { gameId: '68', name: 'Kemet', yearPublished: 2012, minPlayers: 2, maxPlayers: 5, playingTime: 90, rating: 7.9, complexity: 3.1 },
    { gameId: '69', name: 'Inis', yearPublished: 2016, minPlayers: 2, maxPlayers: 4, playingTime: 90, rating: 8.1, complexity: 3.0 },
    { gameId: '70', name: 'Rising Sun', yearPublished: 2018, minPlayers: 3, maxPlayers: 5, playingTime: 90, rating: 7.9, complexity: 3.1 },
    { gameId: '71', name: 'Twilight Imperium (4th Edition)', yearPublished: 2017, minPlayers: 3, maxPlayers: 6, playingTime: 480, rating: 8.6, complexity: 4.3 },
    { gameId: '72', name: 'Eclipse', yearPublished: 2011, minPlayers: 2, maxPlayers: 6, playingTime: 180, rating: 7.9, complexity: 3.6 },
    { gameId: '73', name: 'Star Wars: Outer Rim', yearPublished: 2019, minPlayers: 1, maxPlayers: 4, playingTime: 150, rating: 8.1, complexity: 2.5 },
    { gameId: '74', name: 'Battlestar Galactica', yearPublished: 2008, minPlayers: 3, maxPlayers: 6, playingTime: 180, rating: 7.9, complexity: 3.4 },
    { gameId: '75', name: 'Sekigahara', yearPublished: 2011, minPlayers: 2, maxPlayers: 2, playingTime: 120, rating: 8.2, complexity: 3.1 },
    { gameId: '76', name: 'Root: The Underworld Expansion', yearPublished: 2019, minPlayers: 2, maxPlayers: 6, playingTime: 90, rating: 8.2, complexity: 3.9 },
    { gameId: '77', name: 'Wingspan Asia Expansion', yearPublished: 2021, minPlayers: 1, maxPlayers: 5, playingTime: 70, rating: 8.2, complexity: 2.5 },
    { gameId: '78', name: 'Dune: Imperium', yearPublished: 2020, minPlayers: 1, maxPlayers: 4, playingTime: 120, rating: 8.5, complexity: 3.1 },
    { gameId: '79', name: 'Ark Nova', yearPublished: 2021, minPlayers: 1, maxPlayers: 4, playingTime: 150, rating: 8.5, complexity: 3.7 },
    { gameId: '80', name: 'Cascadia: Landmarks', yearPublished: 2022, minPlayers: 1, maxPlayers: 4, playingTime: 40, rating: 8.0, complexity: 1.9 },
    { gameId: '81', name: 'Res Arcana', yearPublished: 2019, minPlayers: 2, maxPlayers: 4, playingTime: 40, rating: 8.1, complexity: 2.9 },
    { gameId: '82', name: 'Paladins of the West Kingdom', yearPublished: 2019, minPlayers: 1, maxPlayers: 4, playingTime: 90, rating: 8.1, complexity: 3.3 },
    { gameId: '83', name: 'Architects of the West Kingdom', yearPublished: 2018, minPlayers: 1, maxPlayers: 5, playingTime: 80, rating: 7.9, complexity: 3.0 },
    { gameId: '84', name: 'Viscounts of the West Kingdom', yearPublished: 2020, minPlayers: 1, maxPlayers: 5, playingTime: 90, rating: 8.0, complexity: 3.2 },
    { gameId: '85', name: 'Nemesis', yearPublished: 2018, minPlayers: 1, maxPlayers: 5, playingTime: 120, rating: 8.4, complexity: 3.4 },
    { gameId: '86', name: 'Mysterium', yearPublished: 2015, minPlayers: 2, maxPlayers: 7, playingTime: 42, rating: 7.6, complexity: 1.9 },
    { gameId: '87', name: 'Dixit', yearPublished: 2008, minPlayers: 3, maxPlayers: 6, playingTime: 30, rating: 7.2, complexity: 1.2 },
    { gameId: '88', name: 'Just One', yearPublished: 2018, minPlayers: 3, maxPlayers: 7, playingTime: 20, rating: 7.7, complexity: 1.1 },
    { gameId: '89', name: 'Wavelength', yearPublished: 2019, minPlayers: 2, maxPlayers: 12, playingTime: 45, rating: 7.6, complexity: 1.2 },
    { gameId: '90', name: 'The Crew: Mission Deep Sea', yearPublished: 2021, minPlayers: 2, maxPlayers: 5, playingTime: 20, rating: 8.0, complexity: 1.9 },
    { gameId: '91', name: 'Sagrada', yearPublished: 2017, minPlayers: 1, maxPlayers: 4, playingTime: 45, rating: 7.4, complexity: 2.0 },
    { gameId: '92', name: 'Photosynthesis', yearPublished: 2017, minPlayers: 2, maxPlayers: 4, playingTime: 60, rating: 7.4, complexity: 1.9 },
    { gameId: '93', name: 'Calico', yearPublished: 2020, minPlayers: 1, maxPlayers: 4, playingTime: 45, rating: 7.7, complexity: 2.0 },
    { gameId: '94', name: 'Everdell: Pearlbrook', yearPublished: 2020, minPlayers: 1, maxPlayers: 4, playingTime: 80, rating: 8.1, complexity: 3.0 },
    { gameId: '95', name: 'Point Salad', yearPublished: 2019, minPlayers: 2, maxPlayers: 6, playingTime: 30, rating: 7.3, complexity: 1.3 },
    { gameId: '96', name: 'Welcome To...', yearPublished: 2018, minPlayers: 1, maxPlayers: 100, playingTime: 30, rating: 7.5, complexity: 1.8 },
    { gameId: '97', name: 'Ganz Schön Clever', yearPublished: 2018, minPlayers: 1, maxPlayers: 4, playingTime: 30, rating: 7.5, complexity: 1.8 },
    { gameId: '98', name: 'Karuba', yearPublished: 2015, minPlayers: 2, maxPlayers: 4, playingTime: 30, rating: 7.2, complexity: 1.5 },
    { gameId: '99', name: 'Kingdomino', yearPublished: 2016, minPlayers: 2, maxPlayers: 4, playingTime: 20, rating: 7.1, complexity: 1.2 },
    { gameId: '100', name: 'Bunny Kingdom', yearPublished: 2017, minPlayers: 2, maxPlayers: 4, playingTime: 60, rating: 7.4, complexity: 2.1 },
];

const seed = async () => {
    for (const game of games) {
        await docClient.send(new PutCommand({
            TableName: 'BoardGameTrade-Games',
            Item: game,
        }));
        console.log('Inserted:', game.name);
    }
    console.log(`Done. Seeded ${games.length} games.`);
};

seed();